apiVersion: v1
kind: Service

metadata:
  # Nombre del Service dentro de Kubernetes.
  # Otros Pods podrían usar este nombre como DNS interno:
  # pagos-microservice-service.default.svc.cluster.local
  name: pagos-microservice-service

  labels:
    # Etiquetas del propio objeto Service.
    # Sirven para organizar, filtrar o identificar recursos.
    # NO son las que determinan a qué Pods se envía el tráfico.
    #
    # Por consistencia, suele convenir usar el mismo app que el Deployment:
    app: pagos-microservice

spec:
  # Tipo de Service.
  #
  # ClusterIP:
  #   Expone el servicio solo dentro del cluster.
  #
  # NodePort:
  #   Expone el servicio en un puerto del nodo.
  #   Útil para pruebas locales, pero no siempre necesario.
  #
  # LoadBalancer:
  #   Usado normalmente en cloud providers.
  type: NodePort

  ports:
    - # Nombre del puerto.
      # No recomiendo usar "3003" como nombre.
      # Mejor usar un nombre descriptivo.
      name: http

      # Puerto interno del Service.
      # Otros Pods podrían llamar a:
      # pagos-microservice-service:3003
      port: 3003

      # Puerto real donde escucha el contenedor dentro del Pod.
      targetPort: 3003

      protocol: TCP

  selector:
    # ESTE ES EL CAMPO IMPORTANTE.
    #
    # El Service enviará tráfico a los Pods que tengan esta etiqueta:
    # app=pagos-microservice
    #
    # Este valor debe coincidir con:
    # Deployment.spec.template.metadata.labels.app
    app: pagos-microservice